name: Cross Platform

on:
  push:
    branches: [ main, feature/pipeline-test ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly to catch regressions
    - cron: '0 0 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  test-cross-platform:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: cargo test --all-features --verbose

    - name: Build all targets
      run: cargo build --all-targets --all-features

    - name: REPL smoke test
      run: echo "(+ 1 2 3)" | cargo run --example repl --all-features
